# Generated by Django 5.2.14 on 2026-05-16 05:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('protocol', models.CharField(choices=[('modbus', 'Modbus TCP'), ('ethernetip', 'EthernetIP')], max_length=20)),
                ('port', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('starting', 'Starting'), ('running', 'Running'), ('error', 'Error')], default='stopped', max_length=20)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('port__gte', 5020), ('port__lte', 5099), ('protocol', 'modbus')), models.Q(('port__gte', 44818), ('port__lte', 44899), ('protocol', 'ethernetip')), _connector='OR'), name='devices_valid_port_range')],
            },
        ),
    ]
